name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8-openjdk-17-slim

    env:
      MAVEN_CLI_OPTS: "--setting --batch-mode"
      MAVEN_OPTS: "-Dmaven.repo.local=github/home/.m2/repository"

    steps:
      - name: Download the Code
        uses: actions/checkout@v4

      - name: Compile the project
        run: mvn $(MAVEN_CLI_OPTS) clean install

      - name: Cache maven dependencies and plugins
        uses: actions/cache@v4
        with:
          path: github/home/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Upload the Site Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-site
          path: target/