name: Java CI with Maven

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8-openjdk-17-slim

    env:
      MAVEN_CLI_OPTS: "--settings --batch-mode"
      MAVEN_OPTS: "-Dmaven.repo.local=/github/home/.m2/repository"

    steps:
      - name: Download the Code
        uses: actions/checkout@v4

      - name: Cache maven dependencies and plugins
        uses: actions/cache@v4
        with:
          path: github/home/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile the project
        run: mvn $(MAVEN_CLI_OPTS) clean install

      - name: Upload the Site Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-site
          path: target/site/jacoco/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: maven-site
          path: ./jacoco
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./jacoco
      - uses: actions/deploy-pages@v4